export const ACTION_NAMES = {
  // Pump.fun specific actions
  LAUNCH_PUMPFUN_TOKEN: "LAUNCH_PUMPFUN_TOKEN_ACTION",
  GET_TOKEN_PRICE_PUMPFUN: "GET_TOKEN_PRICE_PUMPFUN_ACTION",
  GET_BONDING_CURVE_PUMPFUN: "GET_BONDING_CURVE_PUMPFUN_ACTION",
  GET_BUNDLE_ANALYSIS_PUMPFUN: "GET_BUNDLE_ANALYSIS_PUMPFUN_ACTION",

  // Token data and analysis actions
  GET_TOKEN_DATA_BY_TICKER: "GET_TOKEN_DATA_BY_TICKER_ACTION",
  GET_TOKEN_DATA_BY_ADDRESS: "GET_TOKEN_DATA_BY_ADDRESS_ACTION",
  GET_TOKEN_TOP_HOLDERS: "GET_TOKEN_TOP_HOLDERS_ACTION",
  GET_TOKEN_CHART_ADDRESS: "GET_TOKEN_CHART_ADDRESS_ACTION",
  RUGCHECK_BY_ADDRESS: "RUGCHECK_BY_ADDRESS_ACTION",
  FETCH_PRICE: "FETCH_PRICE_ACTION",
  // Balance and account management actions
  GET_BALANCE: "GET_BALANCE_ACTION",
  GET_BALANCE_OTHER: "GET_BALANCE_OTHER_ACTION",
  GET_TOKEN_BALANCES: "GET_TOKEN_BALANCES_ACTION",
  CLOSE_EMPTY_TOKEN_ACCOUNTS: "CLOSE_EMPTY_TOKEN_ACCOUNTS_ACTION",

  // Transaction and transfer actions
  TRANSFER: "TRANSFER_ACTION",
  JUPITER_SWAP: "JUPITER_SWAP_ACTION",

  // System and utility actions
  GET_TPS: "GET_TPS_ACTION",
  REQUEST_FAUCET_FUNDS: "REQUEST_FAUCET_FUNDS_ACTION",
  ASK_FOR_CONFIRMATION: "ASK_FOR_CONFIRMATION_ACTION",
} as const;
